_BASE_: maskformer/maskformer_R50_bs16_160k_dino.yaml
TOTAL_ITER: 1000
MODEL: 
   META_ARCHITECTURE: "UNET" # "UNET" or "MaskFormer" or "ONEMATRIX"
   ONEMATRIX:
    N_CLASSES: 4
    BILINEAR: True
   UNET:
    N_CHANNELS: 3
    N_CLASSES: 4
    BILINEAR: True
   MASK_FORMER:
    NUM_OBJECT_QUERIES: 4
GWM:
  # MODEL: "UNET"
  # FOCUS_DATA: "car"
  # FOCUS_SERIES: "00007"
  STABLE_SEED: True
  RESOLUTION: (32,32) #(192,352)
  FLOW_RES: (32,32)  #(192,352)
  DATASET: "MOVI_F"
  REBOOST_WHEN_DECREASE: False
  LOSS_MULT:
    GLOBAL: 1.0 #100000000000.0
    OPT: 0.03
    OPT2: 0.0 #0.03
    TRAJ: 0.005
    TRAJ3 : 0.0 #0.005
SOLVER:
  OPTIMIZER: ADAMW
  IMS_PER_BATCH: 8
  WARMUP_ITERS: 1